<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260924150153 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE glycemic_target (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, fasting_min INT NOT NULL, fasting_max INT NOT NULL, post_meal_min INT NOT NULL, post_meal_max INT NOT NULL, bedtime_min INT NOT NULL, bedtime_max INT NOT NULL, patient_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4367AD926B899279 ON glycemic_target (patient_id)');
        $this->addSql('ALTER TABLE glycemic_target ADD CONSTRAINT FK_4367AD926B899279 FOREIGN KEY (patient_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE glycemic_target DROP CONSTRAINT FK_4367AD926B899279');
        $this->addSql('DROP TABLE glycemic_target');
    }
}
