<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260728123605 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE meal_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity DOUBLE PRECISION NOT NULL, calories DOUBLE PRECISION NOT NULL, meal_id INT DEFAULT NULL, aliment_reference_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5C5F6EA639666D6 ON meal_item (meal_id)');
        $this->addSql('CREATE INDEX IDX_5C5F6EAEC9C35F7 ON meal_item (aliment_reference_id)');
        $this->addSql('ALTER TABLE meal_item ADD CONSTRAINT FK_5C5F6EA639666D6 FOREIGN KEY (meal_id) REFERENCES meal (id)');
        $this->addSql('ALTER TABLE meal_item ADD CONSTRAINT FK_5C5F6EAEC9C35F7 FOREIGN KEY (aliment_reference_id) REFERENCES aliment_reference (id)');
        $this->addSql('ALTER TABLE meal ADD type VARCHAR(50) NOT NULL');
        $this->addSql('ALTER TABLE meal ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE meal DROP value');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE meal_item DROP CONSTRAINT FK_5C5F6EA639666D6');
        $this->addSql('ALTER TABLE meal_item DROP CONSTRAINT FK_5C5F6EAEC9C35F7');
        $this->addSql('DROP TABLE meal_item');
        $this->addSql('ALTER TABLE meal ADD value VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE meal DROP type');
        $this->addSql('ALTER TABLE meal DROP created_at');
    }
}
