<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260702140446 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

   public function up(Schema $schema): void
{
    $this->addSql('CREATE TABLE meal (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value VARCHAR(255) NOT NULL, calories INT NOT NULL, date DATE NOT NULL, hour TIME(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
}

    public function down(Schema $schema): void
{
    $this->addSql('DROP TABLE meal');
}
}
