<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260702120800 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }
public function up(Schema $schema): void
{
    $this->addSql('CREATE TABLE blood_sugar (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value NUMERIC(10, 0) NOT NULL, date DATE NOT NULL, time TIME(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
    $this->addSql('ALTER TABLE "user" ADD is_verified BOOLEAN NOT NULL');
}

    public function down(Schema $schema): void
{
    $this->addSql('DROP TABLE blood_sugar');
    $this->addSql('ALTER TABLE "user" DROP is_verified');
}
}
