<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260702131833 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

   public function up(Schema $schema): void
{
    $this->addSql('CREATE TABLE hba1c (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value NUMERIC(10, 0) NOT NULL, date DATE NOT NULL, PRIMARY KEY (id))');
}

   public function down(Schema $schema): void
{
    $this->addSql('DROP TABLE hba1c');
}
}
